[package]
name = "emu"
version = "0.1.0"
authors = ["Erik Hollensbe <github@hollensbe.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinytemplate = "1.1"
serde = { version = "1.0.117", features = ["derive"] }
dirs = "3.0.1"
clap = "2"
libc = "0.2"
tokio = { version = "0.2", features = [ "full" ] }
rtnetlink = "0.6.0"
async-trait = "0.1"
futures = ">=0"
serde_json = ">=0"
