[package]
name = "emu-cli"
version = "0.1.0"
authors = ["Erik Hollensbe <github@hollensbe.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinytemplate = "^1"
serde = { version = "^1", features = [ "derive" ] }
dirs = "^5"
anyhow = "^1"
clap = { version = "^4", features = [ "derive" ] }
tokio = { version = "^1", features = [ "full" ] }
rtnetlink = "^0.14"
async-trait = "^0.1"
futures = "^0.3"
serde_json = "^1"
fork = "^0.1"
byte-unit = "^5"
toml = "^0.8"

[profile.release]
strip = true
lto = true
codegen-units = 24
opt-level = 3
