[package]
name = "emu"
version = "0.1.0"
authors = ["Erik Hollensbe <github@hollensbe.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinytemplate = "*"
serde = { version = "*", features = [ "derive" ] }
dirs = "*"
anyhow = "^1"
clap = { version = "^4", features = [ "derive" ] }
tokio = { version = "*", features = [ "full" ] }
rtnetlink = "*"
async-trait = "*"
futures = "*"
serde_json = "*"
fork = "*"
byte-unit = "*"
toml = "*"

[profile.release]
strip = true
lto = true
codegen-units = 24
opt-level = 3
